### ISSUE TITLE
Unable to run test

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts-v1#124]
#### System information

Commit hash : 41dea4958bd02b7f337a21447455056db6642f57

#### Expected behaviour

```bash
npm i
npm run test
```
should succeed

#### Actual behaviour

`npm run test` failed with

```
> ethstorage-storage-contracts@1.0.0 test
> hardhat test && forge test

Error HH411: The library forge-std, imported from contracts/test/EthStorageContractL2Test.t.sol, is not installed. Try installing it using npm.

HardhatError: HH411: The library forge-std, imported from contracts/test/EthStorageContractL2Test.t.sol, is not installed. Try installing it using npm.
    at Resolver.resolveImport (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:254:15)
    at /root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:188:28
    at async Promise.all (index 0)
    at DependencyGraph._addDependenciesFrom (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:186:5)
    at async Promise.all (index 14)
    at Function.createFromResolvedFiles (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:15:5)
    at Environment._runTaskDefinition (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at Environment.run (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at SimpleTaskDefinition.action (/root/long-term-da-test/sc-test/node_modules/hardhat/src/builtin-tasks/compile.ts:1389:58)
    at Environment._runTaskDefinition (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)

    Caused by: HardhatError: HH401: Library forge-std is not installed.
        at Resolver._resolveLibrarySourceName (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:322:15)
        at Resolver.resolveSourceName (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:103:33)
        at Resolver.resolveImport (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:194:24)
        at /root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:188:28
        at async Promise.all (index 0)
        at DependencyGraph._addDependenciesFrom (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:186:5)
        at async Promise.all (index 14)
        at Function.createFromResolvedFiles (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:15:5)
        at Environment._runTaskDefinition (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
        at Environment.run (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)

        Caused by: Error: Cannot find module 'forge-std/package.json' from '/root/long-term-da-test/sc-test'
            at Function.resolveSync [as sync] (/root/long-term-da-test/sc-test/node_modules/resolve/lib/sync.js:89:15)
            at Resolver._resolveNodeModulesFileFromProjectRoot (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:457:20)
            at Resolver._resolveLibrarySourceName (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:311:30)
            at Resolver.resolveSourceName (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:103:33)
            at Resolver.resolveImport (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/resolver.ts:194:24)
            at /root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:188:28
            at async Promise.all (index 0)
            at DependencyGraph._addDependenciesFrom (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:186:5)
            at async Promise.all (index 14)
            at Function.createFromResolvedFiles (/root/long-term-da-test/sc-test/node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:15:5)
```

**Comment by qzhodl** [comment]
need use npm run install:all to trigger forge install instead of using npm install
